OBJS+=$(BASE_DIR)/renderer/ogles2.0/Colour.o \
	$(BASE_DIR)/renderer/ogles2.0/NonTexturedAlphaShader.o \
	$(BASE_DIR)/renderer/ogles2.0/Renderer.o \
	$(BASE_DIR)/renderer/ogles2.0/ShaderProgram.o \
	$(BASE_DIR)/renderer/ogles2.0/Texture.o \
	$(BASE_DIR)/renderer/ogles2.0/TexturedAlphaShader.o
