include $(BASE_DIR)/math/shapes/Makefile.inc
OBJS += $(BASE_DIR)/math/common.o \
	$(BASE_DIR)/math/fAreEqual.o \
	$(BASE_DIR)/math/fContains.o \
	$(BASE_DIR)/math/fIntersect.o \
	$(BASE_DIR)/math/fOverlap.o \
	$(BASE_DIR)/math/Vec2i.o \
	$(BASE_DIR)/math/Vec2f.o \
	$(BASE_DIR)/math/Vec3i.o \
	$(BASE_DIR)/math/Vec3f.o
