include $(BASE_DIR)/$(PLATFORM)/Makefile.inc
OBJS += $(BASE_DIR)/Colour.o \
	$(BASE_DIR)/CompoundPoly.o \
	$(BASE_DIR)/EEvent.o \
	$(BASE_DIR)/EventManager.o \
	$(BASE_DIR)/Exception.o \
	$(BASE_DIR)/Graphics2d.o \
	$(BASE_DIR)/IWinIO.o \
	$(BASE_DIR)/Poly.o \
	$(BASE_DIR)/Renderer.o \
	$(BASE_DIR)/StackAllocator.o \
	$(BASE_DIR)/StringId.o \
	$(BASE_DIR)/Texture.o \
	$(BASE_DIR)/Vec2f.o \
	$(BASE_DIR)/Vec2i.o
